In [1]:
import pandas as pd

In [82]:
import numpy as np

In [2]:
df=pd.read_csv(r"C:\Users\dilro\Downloads\archive\events.csv")
df

,id_odsp,id_event,sort_order,time,text,event_type,event_type2,side,event_team,opponent,...,player_in,player_out,shot_place,shot_outcome,is_goal,location,bodypart,assist_method,situation,fast_break
0,UFot0hit/,UFot0hit1,1,2,Attempt missed. Mladen Petric (Hamburg) left f...,1,12.0,2,Hamburg SV,Borussia Dortmund,...,NaN,NaN,6.0,2.0,0,9.0,2.0,1,1.0,0
1,UFot0hit/,UFot0hit2,2,4,"Corner, Borussia Dortmund. Conceded by Dennis...",2,NaN,1,Borussia Dortmund,Hamburg SV,...,NaN,NaN,NaN,NaN,0,NaN,NaN,0,NaN,0
2,UFot0hit/,UFot0hit3,3,4,"Corner, Borussia Dortmund. Conceded by Heiko ...",2,NaN,1,Borussia Dortmund,Hamburg SV,...,NaN,NaN,NaN,NaN,0,NaN,NaN,0,NaN,0
3,UFot0hit/,UFot0hit4,4,7,Foul by Sven Bender (Borussia Dortmund).,3,NaN,1,Borussia Dortmund,Hamburg SV,...,NaN,NaN,NaN,NaN,0,NaN,NaN,0,NaN,0
4,UFot0hit/,UFot0hit5,5,7,Gokhan Tore (Hamburg) wins a free kick in the ...,8,NaN,2,Hamburg SV,Borussia Dortmund,...,NaN,NaN,NaN,NaN,0,2.0,NaN,0,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
941004,z5L2OT5E/,z5L2OT5E123,123,92,Lucas Torreira (Sampdoria) wins a free kick in...,8,NaN,2,Sampdoria,Atalanta,...,NaN,NaN,NaN,NaN,0,2.0,NaN,0,NaN,0
941005,z5L2OT5E/,z5L2OT5E124,124,93,"Corner, Sampdoria. Conceded by Andrea Masiello.",2,NaN,2,Sampdoria,Atalanta,...,NaN,NaN,NaN,NaN,0,NaN,NaN,0,NaN,0
941006,z5L2OT5E/,z5L2OT5E125,125,93,Attempt missed. Fabio Quagliarella (Sampdoria)...,1,12.0,2,Sampdoria,Atalanta,...,NaN,NaN,8.0,2.0,0,9.0,1.0,1,3.0,0
941007,z5L2OT5E/,z5L2OT5E126,126,94,Alberto Grassi (Atalanta) wins a free kick on ...,8,NaN,1,Atalanta,Sampdoria,...,NaN,NaN,NaN,NaN,0,4.0,NaN,0,NaN,0
941008,z5L2OT5E/,z5L2OT5E127,127,94,Foul by Pedro Pereira (Sampdoria).,3,NaN,2,Sampdoria,Atalanta,...,NaN,NaN,NaN,NaN,0,NaN,NaN,0,NaN,0

In [4]:
df.size

20702198

In [5]:
df.shape

(941009, 22)

In [8]:
df.columns

Index(['id_odsp', 'id_event', 'sort_order', 'time', 'text', 'event_type',
       'event_type2', 'side', 'event_team', 'opponent', 'player', 'player2',
       'player_in', 'player_out', 'shot_place', 'shot_outcome', 'is_goal',
       'location', 'bodypart', 'assist_method', 'situation', 'fast_break'],
      dtype='object')

In [9]:
df.head()

,id_odsp,id_event,sort_order,time,text,event_type,event_type2,side,event_team,opponent,...,player_in,player_out,shot_place,shot_outcome,is_goal,location,bodypart,assist_method,situation,fast_break
0,UFot0hit/,UFot0hit1,1,2,Attempt missed. Mladen Petric (Hamburg) left f...,1,12.0,2,Hamburg SV,Borussia Dortmund,...,NaN,NaN,6.0,2.0,0,9.0,2.0,1,1.0,0
1,UFot0hit/,UFot0hit2,2,4,"Corner, Borussia Dortmund. Conceded by Dennis...",2,NaN,1,Borussia Dortmund,Hamburg SV,...,NaN,NaN,NaN,NaN,0,NaN,NaN,0,NaN,0
2,UFot0hit/,UFot0hit3,3,4,"Corner, Borussia Dortmund. Conceded by Heiko ...",2,NaN,1,Borussia Dortmund,Hamburg SV,...,NaN,NaN,NaN,NaN,0,NaN,NaN,0,NaN,0
3,UFot0hit/,UFot0hit4,4,7,Foul by Sven Bender (Borussia Dortmund).,3,NaN,1,Borussia Dortmund,Hamburg SV,...,NaN,NaN,NaN,NaN,0,NaN,NaN,0,NaN,0
4,UFot0hit/,UFot0hit5,5,7,Gokhan Tore (Hamburg) wins a free kick in the ...,8,NaN,2,Hamburg SV,Borussia Dortmund,...,NaN,NaN,NaN,NaN,0,2.0,NaN,0,NaN,0

In [10]:
df.tail()

,id_odsp,id_event,sort_order,time,text,event_type,event_type2,side,event_team,opponent,...,player_in,player_out,shot_place,shot_outcome,is_goal,location,bodypart,assist_method,situation,fast_break
941004,z5L2OT5E/,z5L2OT5E123,123,92,Lucas Torreira (Sampdoria) wins a free kick in...,8,NaN,2,Sampdoria,Atalanta,...,NaN,NaN,NaN,NaN,0,2.0,NaN,0,NaN,0
941005,z5L2OT5E/,z5L2OT5E124,124,93,"Corner, Sampdoria. Conceded by Andrea Masiello.",2,NaN,2,Sampdoria,Atalanta,...,NaN,NaN,NaN,NaN,0,NaN,NaN,0,NaN,0
941006,z5L2OT5E/,z5L2OT5E125,125,93,Attempt missed. Fabio Quagliarella (Sampdoria)...,1,12.0,2,Sampdoria,Atalanta,...,NaN,NaN,8.0,2.0,0,9.0,1.0,1,3.0,0
941007,z5L2OT5E/,z5L2OT5E126,126,94,Alberto Grassi (Atalanta) wins a free kick on ...,8,NaN,1,Atalanta,Sampdoria,...,NaN,NaN,NaN,NaN,0,4.0,NaN,0,NaN,0
941008,z5L2OT5E/,z5L2OT5E127,127,94,Foul by Pedro Pereira (Sampdoria).,3,NaN,2,Sampdoria,Atalanta,...,NaN,NaN,NaN,NaN,0,NaN,NaN,0,NaN,0

In [12]:
df.head(2)

,id_odsp,id_event,sort_order,time,text,event_type,event_type2,side,event_team,opponent,...,player_in,player_out,shot_place,shot_outcome,is_goal,location,bodypart,assist_method,situation,fast_break
0,UFot0hit/,UFot0hit1,1,2,Attempt missed. Mladen Petric (Hamburg) left f...,1,12.0,2,Hamburg SV,Borussia Dortmund,...,NaN,NaN,6.0,2.0,0,9.0,2.0,1,1.0,0
1,UFot0hit/,UFot0hit2,2,4,"Corner, Borussia Dortmund. Conceded by Dennis...",2,NaN,1,Borussia Dortmund,Hamburg SV,...,NaN,NaN,NaN,NaN,0,NaN,NaN,0,NaN,0

In [13]:
df.tail(2)

,id_odsp,id_event,sort_order,time,text,event_type,event_type2,side,event_team,opponent,...,player_in,player_out,shot_place,shot_outcome,is_goal,location,bodypart,assist_method,situation,fast_break
941007,z5L2OT5E/,z5L2OT5E126,126,94,Alberto Grassi (Atalanta) wins a free kick on ...,8,NaN,1,Atalanta,Sampdoria,...,NaN,NaN,NaN,NaN,0,4.0,NaN,0,NaN,0
941008,z5L2OT5E/,z5L2OT5E127,127,94,Foul by Pedro Pereira (Sampdoria).,3,NaN,2,Sampdoria,Atalanta,...,NaN,NaN,NaN,NaN,0,NaN,NaN,0,NaN,0

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 941009 entries, 0 to 941008
Data columns (total 22 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   id_odsp        941009 non-null  object
 1   id_event       941009 non-null  object
 2   sort_order     941009 non-null  int64
 3   time           941009 non-null  int64
 4   text           941009 non-null  object
 5   event_type     941009 non-null  int64
 6   event_type2    214293 non-null  float64
 7   side           941009 non-null  int64
 8   event_team     941009 non-null  object
 9   opponent       941009 non-null  object
 10  player         880009 non-null  object
 11  player2        291310 non-null  object
 12  player_in      51715 non-null   object
 13  player_out     51738 non-null   object
 14  shot_place     227459 non-null  float64
 15  shot_outcome   228498 non-null  float64
 16  is_goal        941009 non-null  int64
 17  location       467067 non-null  float64
 18  bodypart       229185 non-null  float64
 19  assist_method  941009 non-null  int64
 20  situation      229137 non-null  float64
 21  fast_break     941009 non-null  int64
dtypes: float64(6), int64(7), object(9)
memory usage: 157.9+ MB

In [16]:
df.describe()

,sort_order,time,event_type,event_type2,side,shot_place,shot_outcome,is_goal,location,bodypart,assist_method,situation,fast_break
count,941009.000000,941009.000000,941009.000000,214293.000000,941009.000000,227459.000000,228498.000000,941009.000000,467067.000000,229185.000000,941009.000000,229137.000000,941009.000000
mean,53.858826,49.663663,4.326575,12.233764,1.481170,5.733693,1.926555,0.025978,6.209073,1.624831,0.264332,1.281316,0.004876
std,32.014268,26.488977,2.995313,0.468850,0.499646,3.326100,0.797055,0.159071,5.421736,0.740400,0.655501,0.709394,0.069655
min,1.000000,0.000000,1.000000,12.000000,1.000000,1.000000,1.000000,0.000000,1.000000,1.000000,0.000000,1.000000,0.000000
25%,27.000000,27.000000,2.000000,12.000000,1.000000,2.000000,1.000000,0.000000,2.000000,1.000000,0.000000,1.000000,0.000000
50%,53.000000,51.000000,3.000000,12.000000,1.000000,5.000000,2.000000,0.000000,3.000000,1.000000,0.000000,1.000000,0.000000
75%,79.000000,73.000000,8.000000,12.000000,2.000000,9.000000,3.000000,0.000000,11.000000,2.000000,0.000000,1.000000,0.000000
max,180.000000,100.000000,11.000000,15.000000,2.000000,13.000000,4.000000,1.000000,19.000000,3.000000,4.000000,4.000000,1.000000

In [19]:
df['opponent']

0         Borussia Dortmund
1                Hamburg SV
2                Hamburg SV
3                Hamburg SV
4         Borussia Dortmund
                ...
941004             Atalanta
941005             Atalanta
941006             Atalanta
941007            Sampdoria
941008             Atalanta
Name: opponent, Length: 941009, dtype: object

In [20]:
df['event_team']

0                Hamburg SV
1         Borussia Dortmund
2         Borussia Dortmund
3         Borussia Dortmund
4                Hamburg SV
                ...
941004            Sampdoria
941005            Sampdoria
941006            Sampdoria
941007             Atalanta
941008            Sampdoria
Name: event_team, Length: 941009, dtype: object

In [21]:
df['text'].unique()

array(['Attempt missed. Mladen Petric (Hamburg) left footed shot from the left side of the box is high and wide to the left. Assisted by Gokhan Tore.',
       'Corner,  Borussia Dortmund. Conceded by Dennis Diekmeier.',
       'Corner,  Borussia Dortmund. Conceded by Heiko Westermann.', ...,
       'Attempt saved. Alejandro Gomez (Atalanta) right footed shot from the left side of the box is saved in the centre of the goal. Assisted by Andrea Petagna.',
       'Substitution, Atalanta. Rafael Toloi replaces Alejandro Gomez.',
       'Attempt missed. Fabio Quagliarella (Sampdoria) right footed shot from the left side of the box misses to the left. Assisted by Lucas Torreira following a corner.'],
      shape=(366076,), dtype=object)

In [29]:
df['location'].dtype

dtype('float64')

In [30]:
df['time'].min()

0

In [31]:
df['time'].max()

100

In [32]:
df['time'].mean()

np.float64(49.663663153062295)

In [33]:
df.isnull()

,id_odsp,id_event,sort_order,time,text,event_type,event_type2,side,event_team,opponent,...,player_in,player_out,shot_place,shot_outcome,is_goal,location,bodypart,assist_method,situation,fast_break
0,False,False,False,False,False,False,False,False,False,False,...,True,True,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,True,False,False,False,...,True,True,True,True,False,True,True,False,True,False
2,False,False,False,False,False,False,True,False,False,False,...,True,True,True,True,False,True,True,False,True,False
3,False,False,False,False,False,False,True,False,False,False,...,True,True,True,True,False,True,True,False,True,False
4,False,False,False,False,False,False,True,False,False,False,...,True,True,True,True,False,False,True,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
941004,False,False,False,False,False,False,True,False,False,False,...,True,True,True,True,False,False,True,False,True,False
941005,False,False,False,False,False,False,True,False,False,False,...,True,True,True,True,False,True,True,False,True,False
941006,False,False,False,False,False,False,False,False,False,False,...,True,True,False,False,False,False,False,False,False,False
941007,False,False,False,False,False,False,True,False,False,False,...,True,True,True,True,False,False,True,False,True,False
941008,False,False,False,False,False,False,True,False,False,False,...,True,True,True,True,False,True,True,False,True,False

In [34]:
df.isnull().sum()

id_odsp               0
id_event              0
sort_order            0
time                  0
text                  0
event_type            0
event_type2      726716
side                  0
event_team            0
opponent              0
player            61000
player2          649699
player_in        889294
player_out       889271
shot_place       713550
shot_outcome     712511
is_goal               0
location         473942
bodypart         711824
assist_method         0
situation        711872
fast_break            0
dtype: int64

In [35]:
df.isna()

,id_odsp,id_event,sort_order,time,text,event_type,event_type2,side,event_team,opponent,...,player_in,player_out,shot_place,shot_outcome,is_goal,location,bodypart,assist_method,situation,fast_break
0,False,False,False,False,False,False,False,False,False,False,...,True,True,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,True,False,False,False,...,True,True,True,True,False,True,True,False,True,False
2,False,False,False,False,False,False,True,False,False,False,...,True,True,True,True,False,True,True,False,True,False
3,False,False,False,False,False,False,True,False,False,False,...,True,True,True,True,False,True,True,False,True,False
4,False,False,False,False,False,False,True,False,False,False,...,True,True,True,True,False,False,True,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
941004,False,False,False,False,False,False,True,False,False,False,...,True,True,True,True,False,False,True,False,True,False
941005,False,False,False,False,False,False,True,False,False,False,...,True,True,True,True,False,True,True,False,True,False
941006,False,False,False,False,False,False,False,False,False,False,...,True,True,False,False,False,False,False,False,False,False
941007,False,False,False,False,False,False,True,False,False,False,...,True,True,True,True,False,False,True,False,True,False
941008,False,False,False,False,False,False,True,False,False,False,...,True,True,True,True,False,True,True,False,True,False

In [36]:
df.isna().sum()

id_odsp               0
id_event              0
sort_order            0
time                  0
text                  0
event_type            0
event_type2      726716
side                  0
event_team            0
opponent              0
player            61000
player2          649699
player_in        889294
player_out       889271
shot_place       713550
shot_outcome     712511
is_goal               0
location         473942
bodypart         711824
assist_method         0
situation        711872
fast_break            0
dtype: int64

In [50]:
df['is_goal'].sum()

np.int64(24446)

In [37]:
df['event_team'].value_counts()

event_team
Juventus         12054
Fiorentina       11802
Real Madrid      11644
AC Milan         11633
AS Roma          11482
                 ...
Crotone           1005
Leganes            991
RB Leipzig         942
Middlesbrough      911
Alaves             888
Name: count, Length: 142, dtype: int64

In [44]:
df['matchs']=df['event_team'] + df['opponent']
df['matchs']

0         Hamburg SVBorussia Dortmund
1         Borussia DortmundHamburg SV
2         Borussia DortmundHamburg SV
3         Borussia DortmundHamburg SV
4         Hamburg SVBorussia Dortmund
                     ...
941004              SampdoriaAtalanta
941005              SampdoriaAtalanta
941006              SampdoriaAtalanta
941007              AtalantaSampdoria
941008              SampdoriaAtalanta
Name: matchs, Length: 941009, dtype: object

In [49]:
df

,id_odsp,id_event,sort_order,time,text,event_type,event_type2,side,event_team,opponent,...,shot_place,shot_outcome,is_goal,location,bodypart,assist_method,situation,fast_break,matchs,substitutions
0,UFot0hit/,UFot0hit1,1,2,Attempt missed. Mladen Petric (Hamburg) left f...,1,12.0,2,Hamburg SV,Borussia Dortmund,...,6.0,2.0,0,9.0,2.0,1,1.0,0,Hamburg SVBorussia Dortmund,NaN
1,UFot0hit/,UFot0hit2,2,4,"Corner, Borussia Dortmund. Conceded by Dennis...",2,NaN,1,Borussia Dortmund,Hamburg SV,...,NaN,NaN,0,NaN,NaN,0,NaN,0,Borussia DortmundHamburg SV,NaN
2,UFot0hit/,UFot0hit3,3,4,"Corner, Borussia Dortmund. Conceded by Heiko ...",2,NaN,1,Borussia Dortmund,Hamburg SV,...,NaN,NaN,0,NaN,NaN,0,NaN,0,Borussia DortmundHamburg SV,NaN
3,UFot0hit/,UFot0hit4,4,7,Foul by Sven Bender (Borussia Dortmund).,3,NaN,1,Borussia Dortmund,Hamburg SV,...,NaN,NaN,0,NaN,NaN,0,NaN,0,Borussia DortmundHamburg SV,NaN
4,UFot0hit/,UFot0hit5,5,7,Gokhan Tore (Hamburg) wins a free kick in the ...,8,NaN,2,Hamburg SV,Borussia Dortmund,...,NaN,NaN,0,2.0,NaN,0,NaN,0,Hamburg SVBorussia Dortmund,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
941004,z5L2OT5E/,z5L2OT5E123,123,92,Lucas Torreira (Sampdoria) wins a free kick in...,8,NaN,2,Sampdoria,Atalanta,...,NaN,NaN,0,2.0,NaN,0,NaN,0,SampdoriaAtalanta,NaN
941005,z5L2OT5E/,z5L2OT5E124,124,93,"Corner, Sampdoria. Conceded by Andrea Masiello.",2,NaN,2,Sampdoria,Atalanta,...,NaN,NaN,0,NaN,NaN,0,NaN,0,SampdoriaAtalanta,NaN
941006,z5L2OT5E/,z5L2OT5E125,125,93,Attempt missed. Fabio Quagliarella (Sampdoria)...,1,12.0,2,Sampdoria,Atalanta,...,8.0,2.0,0,9.0,1.0,1,3.0,0,SampdoriaAtalanta,NaN
941007,z5L2OT5E/,z5L2OT5E126,126,94,Alberto Grassi (Atalanta) wins a free kick on ...,8,NaN,1,Atalanta,Sampdoria,...,NaN,NaN,0,4.0,NaN,0,NaN,0,AtalantaSampdoria,NaN
941008,z5L2OT5E/,z5L2OT5E127,127,94,Foul by Pedro Pereira (Sampdoria).,3,NaN,2,Sampdoria,Atalanta,...,NaN,NaN,0,NaN,NaN,0,NaN,0,SampdoriaAtalanta,NaN

In [51]:
df.dropna()

Empty DataFrame
Columns: [id_odsp, id_event, sort_order, time, text, event_type, event_type2, side, event_team, opponent, player, player2, player_in, player_out, shot_place, shot_outcome, is_goal, location, bodypart, assist_method, situation, fast_break, matchs, substitutions]
Index: []

[0 rows x 24 columns]

In [52]:
df.fillna('nil')

,id_odsp,id_event,sort_order,time,text,event_type,event_type2,side,event_team,opponent,...,shot_place,shot_outcome,is_goal,location,bodypart,assist_method,situation,fast_break,matchs,substitutions
0,UFot0hit/,UFot0hit1,1,2,Attempt missed. Mladen Petric (Hamburg) left f...,1,12.0,2,Hamburg SV,Borussia Dortmund,...,6.0,2.0,0,9.0,2.0,1,1.0,0,Hamburg SVBorussia Dortmund,nil
1,UFot0hit/,UFot0hit2,2,4,"Corner, Borussia Dortmund. Conceded by Dennis...",2,nil,1,Borussia Dortmund,Hamburg SV,...,nil,nil,0,nil,nil,0,nil,0,Borussia DortmundHamburg SV,nil
2,UFot0hit/,UFot0hit3,3,4,"Corner, Borussia Dortmund. Conceded by Heiko ...",2,nil,1,Borussia Dortmund,Hamburg SV,...,nil,nil,0,nil,nil,0,nil,0,Borussia DortmundHamburg SV,nil
3,UFot0hit/,UFot0hit4,4,7,Foul by Sven Bender (Borussia Dortmund).,3,nil,1,Borussia Dortmund,Hamburg SV,...,nil,nil,0,nil,nil,0,nil,0,Borussia DortmundHamburg SV,nil
4,UFot0hit/,UFot0hit5,5,7,Gokhan Tore (Hamburg) wins a free kick in the ...,8,nil,2,Hamburg SV,Borussia Dortmund,...,nil,nil,0,2.0,nil,0,nil,0,Hamburg SVBorussia Dortmund,nil
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
941004,z5L2OT5E/,z5L2OT5E123,123,92,Lucas Torreira (Sampdoria) wins a free kick in...,8,nil,2,Sampdoria,Atalanta,...,nil,nil,0,2.0,nil,0,nil,0,SampdoriaAtalanta,nil
941005,z5L2OT5E/,z5L2OT5E124,124,93,"Corner, Sampdoria. Conceded by Andrea Masiello.",2,nil,2,Sampdoria,Atalanta,...,nil,nil,0,nil,nil,0,nil,0,SampdoriaAtalanta,nil
941006,z5L2OT5E/,z5L2OT5E125,125,93,Attempt missed. Fabio Quagliarella (Sampdoria)...,1,12.0,2,Sampdoria,Atalanta,...,8.0,2.0,0,9.0,1.0,1,3.0,0,SampdoriaAtalanta,nil
941007,z5L2OT5E/,z5L2OT5E126,126,94,Alberto Grassi (Atalanta) wins a free kick on ...,8,nil,1,Atalanta,Sampdoria,...,nil,nil,0,4.0,nil,0,nil,0,AtalantaSampdoria,nil
941008,z5L2OT5E/,z5L2OT5E127,127,94,Foul by Pedro Pereira (Sampdoria).,3,nil,2,Sampdoria,Atalanta,...,nil,nil,0,nil,nil,0,nil,0,SampdoriaAtalanta,nil

In [54]:
df.drop_duplicates()

,id_odsp,id_event,sort_order,time,text,event_type,event_type2,side,event_team,opponent,...,shot_place,shot_outcome,is_goal,location,bodypart,assist_method,situation,fast_break,matchs,substitutions
0,UFot0hit/,UFot0hit1,1,2,Attempt missed. Mladen Petric (Hamburg) left f...,1,12.0,2,Hamburg SV,Borussia Dortmund,...,6.0,2.0,0,9.0,2.0,1,1.0,0,Hamburg SVBorussia Dortmund,NaN
1,UFot0hit/,UFot0hit2,2,4,"Corner, Borussia Dortmund. Conceded by Dennis...",2,NaN,1,Borussia Dortmund,Hamburg SV,...,NaN,NaN,0,NaN,NaN,0,NaN,0,Borussia DortmundHamburg SV,NaN
2,UFot0hit/,UFot0hit3,3,4,"Corner, Borussia Dortmund. Conceded by Heiko ...",2,NaN,1,Borussia Dortmund,Hamburg SV,...,NaN,NaN,0,NaN,NaN,0,NaN,0,Borussia DortmundHamburg SV,NaN
3,UFot0hit/,UFot0hit4,4,7,Foul by Sven Bender (Borussia Dortmund).,3,NaN,1,Borussia Dortmund,Hamburg SV,...,NaN,NaN,0,NaN,NaN,0,NaN,0,Borussia DortmundHamburg SV,NaN
4,UFot0hit/,UFot0hit5,5,7,Gokhan Tore (Hamburg) wins a free kick in the ...,8,NaN,2,Hamburg SV,Borussia Dortmund,...,NaN,NaN,0,2.0,NaN,0,NaN,0,Hamburg SVBorussia Dortmund,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
941004,z5L2OT5E/,z5L2OT5E123,123,92,Lucas Torreira (Sampdoria) wins a free kick in...,8,NaN,2,Sampdoria,Atalanta,...,NaN,NaN,0,2.0,NaN,0,NaN,0,SampdoriaAtalanta,NaN
941005,z5L2OT5E/,z5L2OT5E124,124,93,"Corner, Sampdoria. Conceded by Andrea Masiello.",2,NaN,2,Sampdoria,Atalanta,...,NaN,NaN,0,NaN,NaN,0,NaN,0,SampdoriaAtalanta,NaN
941006,z5L2OT5E/,z5L2OT5E125,125,93,Attempt missed. Fabio Quagliarella (Sampdoria)...,1,12.0,2,Sampdoria,Atalanta,...,8.0,2.0,0,9.0,1.0,1,3.0,0,SampdoriaAtalanta,NaN
941007,z5L2OT5E/,z5L2OT5E126,126,94,Alberto Grassi (Atalanta) wins a free kick on ...,8,NaN,1,Atalanta,Sampdoria,...,NaN,NaN,0,4.0,NaN,0,NaN,0,AtalantaSampdoria,NaN
941008,z5L2OT5E/,z5L2OT5E127,127,94,Foul by Pedro Pereira (Sampdoria).,3,NaN,2,Sampdoria,Atalanta,...,NaN,NaN,0,NaN,NaN,0,NaN,0,SampdoriaAtalanta,NaN

In [55]:
df['situation'].fillna(df['situation'].mean(),inplace=True)
df

C:\Users\dilro\AppData\Local\Temp\ipykernel_20064\1255641323.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['situation'].fillna(df['situation'].mean(),inplace=True)

,id_odsp,id_event,sort_order,time,text,event_type,event_type2,side,event_team,opponent,...,shot_place,shot_outcome,is_goal,location,bodypart,assist_method,situation,fast_break,matchs,substitutions
0,UFot0hit/,UFot0hit1,1,2,Attempt missed. Mladen Petric (Hamburg) left f...,1,12.0,2,Hamburg SV,Borussia Dortmund,...,6.0,2.0,0,9.0,2.0,1,1.000000,0,Hamburg SVBorussia Dortmund,NaN
1,UFot0hit/,UFot0hit2,2,4,"Corner, Borussia Dortmund. Conceded by Dennis...",2,NaN,1,Borussia Dortmund,Hamburg SV,...,NaN,NaN,0,NaN,NaN,0,1.281316,0,Borussia DortmundHamburg SV,NaN
2,UFot0hit/,UFot0hit3,3,4,"Corner, Borussia Dortmund. Conceded by Heiko ...",2,NaN,1,Borussia Dortmund,Hamburg SV,...,NaN,NaN,0,NaN,NaN,0,1.281316,0,Borussia DortmundHamburg SV,NaN
3,UFot0hit/,UFot0hit4,4,7,Foul by Sven Bender (Borussia Dortmund).,3,NaN,1,Borussia Dortmund,Hamburg SV,...,NaN,NaN,0,NaN,NaN,0,1.281316,0,Borussia DortmundHamburg SV,NaN
4,UFot0hit/,UFot0hit5,5,7,Gokhan Tore (Hamburg) wins a free kick in the ...,8,NaN,2,Hamburg SV,Borussia Dortmund,...,NaN,NaN,0,2.0,NaN,0,1.281316,0,Hamburg SVBorussia Dortmund,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
941004,z5L2OT5E/,z5L2OT5E123,123,92,Lucas Torreira (Sampdoria) wins a free kick in...,8,NaN,2,Sampdoria,Atalanta,...,NaN,NaN,0,2.0,NaN,0,1.281316,0,SampdoriaAtalanta,NaN
941005,z5L2OT5E/,z5L2OT5E124,124,93,"Corner, Sampdoria. Conceded by Andrea Masiello.",2,NaN,2,Sampdoria,Atalanta,...,NaN,NaN,0,NaN,NaN,0,1.281316,0,SampdoriaAtalanta,NaN
941006,z5L2OT5E/,z5L2OT5E125,125,93,Attempt missed. Fabio Quagliarella (Sampdoria)...,1,12.0,2,Sampdoria,Atalanta,...,8.0,2.0,0,9.0,1.0,1,3.000000,0,SampdoriaAtalanta,NaN
941007,z5L2OT5E/,z5L2OT5E126,126,94,Alberto Grassi (Atalanta) wins a free kick on ...,8,NaN,1,Atalanta,Sampdoria,...,NaN,NaN,0,4.0,NaN,0,1.281316,0,AtalantaSampdoria,NaN
941008,z5L2OT5E/,z5L2OT5E127,127,94,Foul by Pedro Pereira (Sampdoria).,3,NaN,2,Sampdoria,Atalanta,...,NaN,NaN,0,NaN,NaN,0,1.281316,0,SampdoriaAtalanta,NaN

In [56]:
df['shot_outcome'].fillna(df['shot_outcome'].mode()[0],inplace=True)
df

C:\Users\dilro\AppData\Local\Temp\ipykernel_20064\1609590500.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['shot_outcome'].fillna(df['shot_outcome'].mode()[0],inplace=True)

,id_odsp,id_event,sort_order,time,text,event_type,event_type2,side,event_team,opponent,...,shot_place,shot_outcome,is_goal,location,bodypart,assist_method,situation,fast_break,matchs,substitutions
0,UFot0hit/,UFot0hit1,1,2,Attempt missed. Mladen Petric (Hamburg) left f...,1,12.0,2,Hamburg SV,Borussia Dortmund,...,6.0,2.0,0,9.0,2.0,1,1.000000,0,Hamburg SVBorussia Dortmund,NaN
1,UFot0hit/,UFot0hit2,2,4,"Corner, Borussia Dortmund. Conceded by Dennis...",2,NaN,1,Borussia Dortmund,Hamburg SV,...,NaN,2.0,0,NaN,NaN,0,1.281316,0,Borussia DortmundHamburg SV,NaN
2,UFot0hit/,UFot0hit3,3,4,"Corner, Borussia Dortmund. Conceded by Heiko ...",2,NaN,1,Borussia Dortmund,Hamburg SV,...,NaN,2.0,0,NaN,NaN,0,1.281316,0,Borussia DortmundHamburg SV,NaN
3,UFot0hit/,UFot0hit4,4,7,Foul by Sven Bender (Borussia Dortmund).,3,NaN,1,Borussia Dortmund,Hamburg SV,...,NaN,2.0,0,NaN,NaN,0,1.281316,0,Borussia DortmundHamburg SV,NaN
4,UFot0hit/,UFot0hit5,5,7,Gokhan Tore (Hamburg) wins a free kick in the ...,8,NaN,2,Hamburg SV,Borussia Dortmund,...,NaN,2.0,0,2.0,NaN,0,1.281316,0,Hamburg SVBorussia Dortmund,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
941004,z5L2OT5E/,z5L2OT5E123,123,92,Lucas Torreira (Sampdoria) wins a free kick in...,8,NaN,2,Sampdoria,Atalanta,...,NaN,2.0,0,2.0,NaN,0,1.281316,0,SampdoriaAtalanta,NaN
941005,z5L2OT5E/,z5L2OT5E124,124,93,"Corner, Sampdoria. Conceded by Andrea Masiello.",2,NaN,2,Sampdoria,Atalanta,...,NaN,2.0,0,NaN,NaN,0,1.281316,0,SampdoriaAtalanta,NaN
941006,z5L2OT5E/,z5L2OT5E125,125,93,Attempt missed. Fabio Quagliarella (Sampdoria)...,1,12.0,2,Sampdoria,Atalanta,...,8.0,2.0,0,9.0,1.0,1,3.000000,0,SampdoriaAtalanta,NaN
941007,z5L2OT5E/,z5L2OT5E126,126,94,Alberto Grassi (Atalanta) wins a free kick on ...,8,NaN,1,Atalanta,Sampdoria,...,NaN,2.0,0,4.0,NaN,0,1.281316,0,AtalantaSampdoria,NaN
941008,z5L2OT5E/,z5L2OT5E127,127,94,Foul by Pedro Pereira (Sampdoria).,3,NaN,2,Sampdoria,Atalanta,...,NaN,2.0,0,NaN,NaN,0,1.281316,0,SampdoriaAtalanta,NaN

In [58]:
df.loc[0,'opponent']

'Borussia Dortmund'

In [59]:
df.loc[4,'text']

'Gokhan Tore (Hamburg) wins a free kick in the defensive half.'

In [60]:
df.loc[3:4,['opponent','text']]

            opponent                                               text
3         Hamburg SV           Foul by Sven Bender (Borussia Dortmund).
4  Borussia Dortmund  Gokhan Tore (Hamburg) wins a free kick in the ...

In [57]:
df.iloc[3,2]

np.int64(4)

In [62]:
df[df['time']>30]

,id_odsp,id_event,sort_order,time,text,event_type,event_type2,side,event_team,opponent,...,shot_place,shot_outcome,is_goal,location,bodypart,assist_method,situation,fast_break,matchs,substitutions
27,UFot0hit/,UFot0hit28,28,31,Foul by Kevin Grosskreutz (Borussia Dortmund).,3,NaN,1,Borussia Dortmund,Hamburg SV,...,NaN,2.0,0,NaN,NaN,0,1.281316,0,Borussia DortmundHamburg SV,NaN
28,UFot0hit/,UFot0hit29,29,31,Gokhan Tore (Hamburg) wins a free kick on the ...,8,NaN,2,Hamburg SV,Borussia Dortmund,...,NaN,2.0,0,5.0,NaN,0,1.281316,0,Hamburg SVBorussia Dortmund,NaN
29,UFot0hit/,UFot0hit30,30,32,Roman Weidenfeller (Borussia Dortmund) wins a ...,8,NaN,1,Borussia Dortmund,Hamburg SV,...,NaN,2.0,0,2.0,NaN,0,1.281316,0,Borussia DortmundHamburg SV,NaN
30,UFot0hit/,UFot0hit31,31,32,"Corner, Hamburg. Conceded by Ilkay Gundogan.",2,NaN,2,Hamburg SV,Borussia Dortmund,...,NaN,2.0,0,NaN,NaN,0,1.281316,0,Hamburg SVBorussia Dortmund,NaN
31,UFot0hit/,UFot0hit32,32,32,Foul by Gojko Kacar (Hamburg).,3,NaN,2,Hamburg SV,Borussia Dortmund,...,NaN,2.0,0,NaN,NaN,0,1.281316,0,Hamburg SVBorussia Dortmund,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
941004,z5L2OT5E/,z5L2OT5E123,123,92,Lucas Torreira (Sampdoria) wins a free kick in...,8,NaN,2,Sampdoria,Atalanta,...,NaN,2.0,0,2.0,NaN,0,1.281316,0,SampdoriaAtalanta,NaN
941005,z5L2OT5E/,z5L2OT5E124,124,93,"Corner, Sampdoria. Conceded by Andrea Masiello.",2,NaN,2,Sampdoria,Atalanta,...,NaN,2.0,0,NaN,NaN,0,1.281316,0,SampdoriaAtalanta,NaN
941006,z5L2OT5E/,z5L2OT5E125,125,93,Attempt missed. Fabio Quagliarella (Sampdoria)...,1,12.0,2,Sampdoria,Atalanta,...,8.0,2.0,0,9.0,1.0,1,3.000000,0,SampdoriaAtalanta,NaN
941007,z5L2OT5E/,z5L2OT5E126,126,94,Alberto Grassi (Atalanta) wins a free kick on ...,8,NaN,1,Atalanta,Sampdoria,...,NaN,2.0,0,4.0,NaN,0,1.281316,0,AtalantaSampdoria,NaN
941008,z5L2OT5E/,z5L2OT5E127,127,94,Foul by Pedro Pereira (Sampdoria).,3,NaN,2,Sampdoria,Atalanta,...,NaN,2.0,0,NaN,NaN,0,1.281316,0,SampdoriaAtalanta,NaN

In [77]:
df[(df['time']<10) & (df['sort_order']<10)]

,id_odsp,id_event,sort_order,time,text,event_type,event_type2,side,event_team,opponent,...,shot_place,shot_outcome,is_goal,location,bodypart,assist_method,situation,fast_break,matchs,substitutions
0,UFot0hit/,UFot0hit1,1,2,Attempt missed. Mladen Petric (Hamburg) left f...,1,12.0,2,Hamburg SV,Borussia Dortmund,...,6.0,2.0,0,9.0,2.0,1,1.000000,0,Hamburg SVBorussia Dortmund,NaN
1,UFot0hit/,UFot0hit2,2,4,"Corner, Borussia Dortmund. Conceded by Dennis...",2,NaN,1,Borussia Dortmund,Hamburg SV,...,NaN,2.0,0,NaN,NaN,0,1.281316,0,Borussia DortmundHamburg SV,NaN
2,UFot0hit/,UFot0hit3,3,4,"Corner, Borussia Dortmund. Conceded by Heiko ...",2,NaN,1,Borussia Dortmund,Hamburg SV,...,NaN,2.0,0,NaN,NaN,0,1.281316,0,Borussia DortmundHamburg SV,NaN
3,UFot0hit/,UFot0hit4,4,7,Foul by Sven Bender (Borussia Dortmund).,3,NaN,1,Borussia Dortmund,Hamburg SV,...,NaN,2.0,0,NaN,NaN,0,1.281316,0,Borussia DortmundHamburg SV,NaN
4,UFot0hit/,UFot0hit5,5,7,Gokhan Tore (Hamburg) wins a free kick in the ...,8,NaN,2,Hamburg SV,Borussia Dortmund,...,NaN,2.0,0,2.0,NaN,0,1.281316,0,Hamburg SVBorussia Dortmund,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
940890,z5L2OT5E/,z5L2OT5E3,3,2,Attempt saved. Dennis Praet (Sampdoria) right ...,1,12.0,2,Sampdoria,Atalanta,...,4.0,1.0,0,15.0,1.0,1,1.000000,0,SampdoriaAtalanta,NaN
940891,z5L2OT5E/,z5L2OT5E4,4,2,Bruno Fernandes (Sampdoria) wins a free kick i...,8,NaN,2,Sampdoria,Atalanta,...,NaN,2.0,0,1.0,NaN,0,1.281316,0,SampdoriaAtalanta,NaN
940892,z5L2OT5E/,z5L2OT5E5,5,2,Foul by Remo Freuler (Atalanta).,3,NaN,1,Atalanta,Sampdoria,...,NaN,2.0,0,NaN,NaN,0,1.281316,0,AtalantaSampdoria,NaN
940893,z5L2OT5E/,z5L2OT5E6,6,5,Filippo Melegoni (Atalanta) wins a free kick o...,8,NaN,1,Atalanta,Sampdoria,...,NaN,2.0,0,5.0,NaN,0,1.281316,0,AtalantaSampdoria,NaN
940894,z5L2OT5E/,z5L2OT5E7,7,5,Foul by Lucas Torreira (Sampdoria).,3,NaN,2,Sampdoria,Atalanta,...,NaN,2.0,0,NaN,NaN,0,1.281316,0,SampdoriaAtalanta,NaN

In [78]:
df.sort_values(by='side',ascending=False)

,id_odsp,id_event,sort_order,time,text,event_type,event_type2,side,event_team,opponent,...,shot_place,shot_outcome,is_goal,location,bodypart,assist_method,situation,fast_break,matchs,substitutions
0,UFot0hit/,UFot0hit1,1,2,Attempt missed. Mladen Petric (Hamburg) left f...,1,12.0,2,Hamburg SV,Borussia Dortmund,...,6.0,2.0,0,9.0,2.0,1,1.000000,0,Hamburg SVBorussia Dortmund,NaN
517938,EX9VAFWh/,EX9VAFWh58,58,64,Foul by Gianni Bruno (Evian Thonon Gaillard).,3,NaN,2,Evian Thonon Gaillard,AS Monaco,...,NaN,2.0,0,NaN,NaN,0,1.281316,0,Evian Thonon GaillardAS Monaco,NaN
517941,EX9VAFWh/,EX9VAFWh61,61,65,"Corner, Evian Thonon Gaillard. Conceded by Ri...",2,NaN,2,Evian Thonon Gaillard,AS Monaco,...,NaN,2.0,0,NaN,NaN,0,1.281316,0,Evian Thonon GaillardAS Monaco,NaN
517942,EX9VAFWh/,EX9VAFWh62,62,66,"Corner, Evian Thonon Gaillard. Conceded by An...",2,NaN,2,Evian Thonon Gaillard,AS Monaco,...,NaN,2.0,0,NaN,NaN,0,1.281316,0,Evian Thonon GaillardAS Monaco,NaN
517943,EX9VAFWh/,EX9VAFWh63,63,66,Attempt blocked. CA©dric Cambon (Evian Thonon ...,1,NaN,2,Evian Thonon Gaillard,AS Monaco,...,2.0,3.0,0,13.0,3.0,0,1.000000,0,Evian Thonon GaillardAS Monaco,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
545008,Kzjg8ERk/,Kzjg8ERk30,30,38,Attempt missed. Muhamed Besic (Everton) right ...,1,NaN,1,Everton,Hull,...,9.0,2.0,0,15.0,1.0,0,2.000000,0,EvertonHull,NaN
545007,Kzjg8ERk/,Kzjg8ERk29,29,38,Attempt blocked. Leon Osman (Everton) left foo...,1,12.0,1,Everton,Hull,...,2.0,3.0,0,3.0,2.0,1,1.000000,0,EvertonHull,NaN
545005,Kzjg8ERk/,Kzjg8ERk27,27,37,Leighton Baines (Everton) wins a free kick on ...,8,NaN,1,Everton,Hull,...,NaN,2.0,0,4.0,NaN,0,1.281316,0,EvertonHull,NaN
545004,Kzjg8ERk/,Kzjg8ERk26,26,33,"Goal! Goal! Everton 1, Hull City 0. Ro...",1,12.0,1,Everton,Hull,...,3.0,1.0,1,3.0,2.0,1,1.000000,0,EvertonHull,NaN
470504,0lrsF4ji/,0lrsF4ji61,61,56,Foul by Marcelo (Real Madrid).,3,NaN,1,Real Madrid,Valencia,...,NaN,2.0,0,NaN,NaN,0,1.281316,0,Real MadridValencia,NaN

In [79]:
df.sort_values(by=['time','opponent'],ascending=[True,False])

,id_odsp,id_event,sort_order,time,text,event_type,event_type2,side,event_team,opponent,...,shot_place,shot_outcome,is_goal,location,bodypart,assist_method,situation,fast_break,matchs,substitutions
371243,UZlwdQ7b/,UZlwdQ7b2,2,0,Foul by Raheem Sterling (Liverpool).,3,NaN,1,Liverpool,West Ham,...,NaN,2.0,0,NaN,NaN,0,1.281316,0,LiverpoolWest Ham,NaN
388901,jVWrmK00/,jVWrmK001,1,0,"Substitution, Cardiff City. Craig Bellamy repl...",7,NaN,1,Cardiff,West Ham,...,NaN,2.0,0,NaN,NaN,0,1.281316,0,CardiffWest Ham,craig bellamypeter odemwingie
475877,0WEr7Kjt/,0WEr7Kjt1,1,0,Foul by Samir Nasri (Manchester City).,3,NaN,1,Manchester City,West Ham,...,NaN,2.0,0,NaN,NaN,0,1.281316,0,Manchester CityWest Ham,NaN
563859,lhahpTe4/,lhahpTe41,1,0,James Morrison (West Bromwich Albion) wins a f...,8,NaN,2,West Brom,West Ham,...,NaN,2.0,0,4.0,NaN,0,1.281316,0,West BromWest Ham,NaN
572716,4rl9B5f3/,4rl9B5f31,1,0,"Corner, Hull City. Conceded by Mark Noble.",2,NaN,2,Hull,West Ham,...,NaN,2.0,0,NaN,NaN,0,1.281316,0,HullWest Ham,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
536761,IVwp48Un/,IVwp48Un102,102,99,Attempt blocked. Santiago Cazorla (Arsenal) ri...,1,12.0,1,Arsenal,Manchester Utd,...,2.0,3.0,0,15.0,1.0,1,1.000000,0,ArsenalManchester Utd,NaN
559906,2HjCGcy7/,2HjCGcy798,98,99,Attempt saved. Santiago Cazorla (Arsenal) left...,1,12.0,2,Arsenal,Liverpool,...,3.0,1.0,0,15.0,2.0,1,1.000000,0,ArsenalLiverpool,NaN
559907,2HjCGcy7/,2HjCGcy799,99,99,"Corner, Arsenal. Conceded by Martin Skrtel.",2,NaN,2,Arsenal,Liverpool,...,NaN,2.0,0,NaN,NaN,0,1.281316,0,ArsenalLiverpool,NaN
924639,zmvq2Ub0/,zmvq2Ub082,82,99,"Corner, Liverpool. Conceded by Dominic Calver...",2,NaN,2,Liverpool,Everton,...,NaN,2.0,0,NaN,NaN,0,1.281316,0,LiverpoolEverton,NaN
559908,2HjCGcy7/,2HjCGcy7100,100,100,Attempt blocked. Danny Welbeck (Arsenal) right...,1,12.0,2,Arsenal,Liverpool,...,2.0,3.0,0,3.0,1.0,2,1.000000,0,ArsenalLiverpool,NaN

In [80]:
df.reset_index()

,index,id_odsp,id_event,sort_order,time,text,event_type,event_type2,side,event_team,...,shot_place,shot_outcome,is_goal,location,bodypart,assist_method,situation,fast_break,matchs,substitutions
0,0,UFot0hit/,UFot0hit1,1,2,Attempt missed. Mladen Petric (Hamburg) left f...,1,12.0,2,Hamburg SV,...,6.0,2.0,0,9.0,2.0,1,1.000000,0,Hamburg SVBorussia Dortmund,NaN
1,1,UFot0hit/,UFot0hit2,2,4,"Corner, Borussia Dortmund. Conceded by Dennis...",2,NaN,1,Borussia Dortmund,...,NaN,2.0,0,NaN,NaN,0,1.281316,0,Borussia DortmundHamburg SV,NaN
2,2,UFot0hit/,UFot0hit3,3,4,"Corner, Borussia Dortmund. Conceded by Heiko ...",2,NaN,1,Borussia Dortmund,...,NaN,2.0,0,NaN,NaN,0,1.281316,0,Borussia DortmundHamburg SV,NaN
3,3,UFot0hit/,UFot0hit4,4,7,Foul by Sven Bender (Borussia Dortmund).,3,NaN,1,Borussia Dortmund,...,NaN,2.0,0,NaN,NaN,0,1.281316,0,Borussia DortmundHamburg SV,NaN
4,4,UFot0hit/,UFot0hit5,5,7,Gokhan Tore (Hamburg) wins a free kick in the ...,8,NaN,2,Hamburg SV,...,NaN,2.0,0,2.0,NaN,0,1.281316,0,Hamburg SVBorussia Dortmund,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
941004,941004,z5L2OT5E/,z5L2OT5E123,123,92,Lucas Torreira (Sampdoria) wins a free kick in...,8,NaN,2,Sampdoria,...,NaN,2.0,0,2.0,NaN,0,1.281316,0,SampdoriaAtalanta,NaN
941005,941005,z5L2OT5E/,z5L2OT5E124,124,93,"Corner, Sampdoria. Conceded by Andrea Masiello.",2,NaN,2,Sampdoria,...,NaN,2.0,0,NaN,NaN,0,1.281316,0,SampdoriaAtalanta,NaN
941006,941006,z5L2OT5E/,z5L2OT5E125,125,93,Attempt missed. Fabio Quagliarella (Sampdoria)...,1,12.0,2,Sampdoria,...,8.0,2.0,0,9.0,1.0,1,3.000000,0,SampdoriaAtalanta,NaN
941007,941007,z5L2OT5E/,z5L2OT5E126,126,94,Alberto Grassi (Atalanta) wins a free kick on ...,8,NaN,1,Atalanta,...,NaN,2.0,0,4.0,NaN,0,1.281316,0,AtalantaSampdoria,NaN
941008,941008,z5L2OT5E/,z5L2OT5E127,127,94,Foul by Pedro Pereira (Sampdoria).,3,NaN,2,Sampdoria,...,NaN,2.0,0,NaN,NaN,0,1.281316,0,SampdoriaAtalanta,NaN

In [83]:
df.replace(np.nan,0)

,id_odsp,id_event,sort_order,time,text,event_type,event_type2,side,event_team,opponent,...,shot_place,shot_outcome,is_goal,location,bodypart,assist_method,situation,fast_break,matchs,substitutions
0,UFot0hit/,UFot0hit1,1,2,Attempt missed. Mladen Petric (Hamburg) left f...,1,12.0,2,Hamburg SV,Borussia Dortmund,...,6.0,2.0,0,9.0,2.0,1,1.000000,0,Hamburg SVBorussia Dortmund,0
1,UFot0hit/,UFot0hit2,2,4,"Corner, Borussia Dortmund. Conceded by Dennis...",2,0.0,1,Borussia Dortmund,Hamburg SV,...,0.0,2.0,0,0.0,0.0,0,1.281316,0,Borussia DortmundHamburg SV,0
2,UFot0hit/,UFot0hit3,3,4,"Corner, Borussia Dortmund. Conceded by Heiko ...",2,0.0,1,Borussia Dortmund,Hamburg SV,...,0.0,2.0,0,0.0,0.0,0,1.281316,0,Borussia DortmundHamburg SV,0
3,UFot0hit/,UFot0hit4,4,7,Foul by Sven Bender (Borussia Dortmund).,3,0.0,1,Borussia Dortmund,Hamburg SV,...,0.0,2.0,0,0.0,0.0,0,1.281316,0,Borussia DortmundHamburg SV,0
4,UFot0hit/,UFot0hit5,5,7,Gokhan Tore (Hamburg) wins a free kick in the ...,8,0.0,2,Hamburg SV,Borussia Dortmund,...,0.0,2.0,0,2.0,0.0,0,1.281316,0,Hamburg SVBorussia Dortmund,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
941004,z5L2OT5E/,z5L2OT5E123,123,92,Lucas Torreira (Sampdoria) wins a free kick in...,8,0.0,2,Sampdoria,Atalanta,...,0.0,2.0,0,2.0,0.0,0,1.281316,0,SampdoriaAtalanta,0
941005,z5L2OT5E/,z5L2OT5E124,124,93,"Corner, Sampdoria. Conceded by Andrea Masiello.",2,0.0,2,Sampdoria,Atalanta,...,0.0,2.0,0,0.0,0.0,0,1.281316,0,SampdoriaAtalanta,0
941006,z5L2OT5E/,z5L2OT5E125,125,93,Attempt missed. Fabio Quagliarella (Sampdoria)...,1,12.0,2,Sampdoria,Atalanta,...,8.0,2.0,0,9.0,1.0,1,3.000000,0,SampdoriaAtalanta,0
941007,z5L2OT5E/,z5L2OT5E126,126,94,Alberto Grassi (Atalanta) wins a free kick on ...,8,0.0,1,Atalanta,Sampdoria,...,0.0,2.0,0,4.0,0.0,0,1.281316,0,AtalantaSampdoria,0
941008,z5L2OT5E/,z5L2OT5E127,127,94,Foul by Pedro Pereira (Sampdoria).,3,0.0,2,Sampdoria,Atalanta,...,0.0,2.0,0,0.0,0.0,0,1.281316,0,SampdoriaAtalanta,0

In [84]:
df.groupby('event_team')['time'].mean()

event_team
AC Ajaccio           49.022047
AC Milan             49.655377
AJ Auxerre           49.922379
AS Monaco            49.680000
AS Nancy Lorraine    49.706550
                       ...
Villarreal           49.537949
Watford              51.715664
Werder Bremen        48.852231
West Brom            50.954085
West Ham             50.000500
Name: time, Length: 142, dtype: float64

In [86]:
df.pivot_table(index='event_team',columns='opponent',values='is_goal',aggfunc='sum',fill_value=0)

opponent,AC Ajaccio,AC Milan,AJ Auxerre,AS Monaco,AS Nancy Lorraine,AS Roma,Alaves,Almeria,Angers,Arsenal,...,Udinese,Valencia,Valenciennes,VfB Stuttgart,VfL Wolfsburg,Villarreal,Watford,Werder Bremen,West Brom,West Ham
event_team,,,,,,,,,,,,,,,,,,,,,
AC Ajaccio,0,0,3,1,4,0,0,0,0,0,...,0,0,10,0,0,0,0,0,0,0
AC Milan,0,0,0,0,0,12,0,0,0,0,...,12,0,0,0,0,0,0,0,0,0
AJ Auxerre,5,0,0,0,1,0,0,0,0,0,...,0,0,3,0,0,0,0,0,0,0
AS Monaco,5,0,0,0,6,0,0,0,3,0,...,0,0,3,0,0,0,0,0,0,0
AS Nancy Lorraine,3,0,3,0,0,0,0,0,2,0,...,0,0,2,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Villarreal,0,0,0,0,0,0,0,7,0,0,...,0,10,0,0,0,0,0,0,0,0
Watford,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,2,7
Werder Bremen,0,0,0,0,0,0,0,0,0,0,...,0,0,0,22,17,0,0,0,0,0
West Brom,0,0,0,0,0,0,0,0,0,4,...,0,0,0,0,0,0,3,0,0,11
West Ham,0,0,0,0,0,0,0,0,0,9,...,0,0,0,0,0,0,5,0,12,0