In [1]:
import pandas as pd

In [2]:
a={'Student_ID':[101,102,103,104,105,106,107,108],
'Name':['Ali','Sara','John','Emma','David','Liya','Arjun','Meera'],
'Age':[21,22,20,23,21,22,23,20],
'Department':['CS','IT','CS','EC','IT','CS','EC','IT'],
'Marks':[85,40,90,60,75,88,55,95],
'Attendance':[92,75,88,95,80,91,70,98]}

In [3]:
df=pd.DataFrame(a)
df

   Student_ID   Name  Age Department  Marks  Attendance
0         101    Ali   21         CS     85          92
1         102   Sara   22         IT     40          75
2         103   John   20         CS     90          88
3         104   Emma   23         EC     60          95
4         105  David   21         IT     75          80
5         106   Liya   22         CS     88          91
6         107  Arjun   23         EC     55          70
7         108  Meera   20         IT     95          98

## 1

In [4]:
df[df['Marks']>85]

   Student_ID   Name  Age Department  Marks  Attendance
2         103   John   20         CS     90          88
5         106   Liya   22         CS     88          91
7         108  Meera   20         IT     95          98

## 2

In [5]:
df[(df['Attendance']>80) & (df['Department']=='IT')]

   Student_ID   Name  Age Department  Marks  Attendance
7         108  Meera   20         IT     95          98

## 3

In [6]:
df.sort_values(by='Marks',ascending=False)

   Student_ID   Name  Age Department  Marks  Attendance
7         108  Meera   20         IT     95          98
2         103   John   20         CS     90          88
5         106   Liya   22         CS     88          91
0         101    Ali   21         CS     85          92
4         105  David   21         IT     75          80
3         104   Emma   23         EC     60          95
6         107  Arjun   23         EC     55          70
1         102   Sara   22         IT     40          75

## 4

In [7]:
df[(df['Marks']>=60) & (df['Marks']<=90)]

   Student_ID   Name  Age Department  Marks  Attendance
0         101    Ali   21         CS     85          92
2         103   John   20         CS     90          88
3         104   Emma   23         EC     60          95
4         105  David   21         IT     75          80
5         106   Liya   22         CS     88          91

## 5

In [8]:
df[df['Age']==21][['Name','Department']]

    Name Department
0    Ali         CS
4  David         IT

## 6

In [9]:
avg_marks=df['Marks'].mean()
df[(df['Department']=='CS') & (df['Marks']>avg_marks)]

   Student_ID  Name  Age Department  Marks  Attendance
0         101   Ali   21         CS     85          92
2         103  John   20         CS     90          88
5         106  Liya   22         CS     88          91

## 7

In [10]:
df.sort_values(by=['Department','Marks'],ascending=[True,False])

   Student_ID   Name  Age Department  Marks  Attendance
2         103   John   20         CS     90          88
5         106   Liya   22         CS     88          91
0         101    Ali   21         CS     85          92
3         104   Emma   23         EC     60          95
6         107  Arjun   23         EC     55          70
7         108  Meera   20         IT     95          98
4         105  David   21         IT     75          80
1         102   Sara   22         IT     40          75

## 8

In [11]:
min_attendance=df['Attendance'].min()
df[df['Attendance']==min_attendance]

   Student_ID   Name  Age Department  Marks  Attendance
6         107  Arjun   23         EC     55          70

## 9

In [12]:
df[(df['Marks']>90) | (df['Attendance']>95)]

   Student_ID   Name  Age Department  Marks  Attendance
7         108  Meera   20         IT     95          98

## 10

In [13]:
sorted_marks=df['Marks'].sort_values(ascending=False)
second_highest=sorted_marks.iloc[1]
df[df['Marks']==second_highest]

   Student_ID  Name  Age Department  Marks  Attendance
2         103  John   20         CS     90          88